name: aws deployment

on:
    push:
        branches:
            - main

jobs:
    build:
        name: build to static files
        runs-on: ubuntu-latest

        env:
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

        steps:
            - uses: actions/checkout@v4
            - name: yarn install and yarn build
              run: |
                  yarn install
                  CI=false yarn build
            - uses: actions/upload-artifact@master
              with:
                  name: apex-website-database-ui-staging artifacts
                  path: dist/
    deploy:
        name: Deploy to AWS.
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download built artifact
              uses: actions/download-artifact@master
              with:
                  name: apex-website-database-ui-staging artifacts
                  path: dist

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: ap-southeast-1
            - name: Deploy static site to S3 bucket
              run: aws s3 sync ./dist/ s3://apex-website-database-ui-stg --delete
